### ISSUE TITLE
Ordnernamen

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-filename-sanitizer-bundle#1]
Hallo,
ich möchte mich auch auf diesem Weg für die sehr schöne Extension bedanken.

Könnte diese aauch noch auf die Ordnernamen erweitert werden, wie die alte?

Ich habe die Erfahrung machen müssen, dass 90% der Contao-CMS-Kunden zwar lernen können, die Dateinamen ascii7-konform zu erstellen, aber im Backend bei der Erstellung der Ordner das Erlernte sofort wieder vergessen. Auch Nachschulungen ändern nichts.

**Comment by Defcon0** [comment]
Hallo,

diese Erfahrung habe ich auch gemacht ;-) Ordner-Namen werden jetzt auch unterstützt:

https://github.com/heimrichhannot/contao-filename-sanitizer-bundle/tree/1.1.0

**Comment by chriza** [comment]
Vielen lieben Dank. Viele Schweißtropfen weniger :o)
