### ISSUE TITLE
Contao 4.9.2

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-filename-sanitizer-bundle#10]
Hallo,

mit einer frischen Contao 4.9.2 Installation wird beim Erzeugen/Speichern von Seiten eine "weiße Seite" generiert.

**Comment by Defcon0** [comment]
Hallo,

bitte aktiviere den Dev-Modus und poste den Fehler. Du findest diesen auch den logs. Danke!

**Comment by chriza** [comment]
Hallo,
nach weiterem Testen habe ich festgestellt, daß nicht diese Extension das Problem verursacht. Der Fehler trat zufällig auf, nachdem ich diese Extension installiert hatte.
