### ISSUE TITLE
Mehre Dateien bearbeiten in Dateimanager?

### ISSUE THREAD

**Issue by pswerbung** [heimrichhannot/contao-filename-sanitizer-bundle#11]
Sehr cool, dass das Regelwerk beim Speichern einer bestehenden Datei auch funktioniert =)

Allerdings gibt es beim Batch-Editing noch einen Fehler. Das wäre natürlich nochmals ein cooles Feature, wenn man ganze Verzeichnise per Klick bereinigen könnte … ?!

Internal Server Error
Was ist das Problem?

Invalid resource files/content/….jpg

**Comment by Defcon0** [comment]
Ja, ich glaube, den Batch-Modus hatte ich etwas vernachlässigt ;-) Ich komme allerdings nicht sofort dazu, mir das anzuschauen.

**Comment by Defcon0** [comment]
Erledigt mit 2.1.0 . (Alle Infos siehe https://github.com/heimrichhannot/contao-filename-sanitizer-bundle/blob/master/README.md)

**Wichtig**: Da das Feature ganz neu ist, bitte lege UNBEDINGT ein Backup von `tl_files` und dem `files`-Ordner an!

Da das klar ein Entwickler-Feature ist, habe ich es als Command umgesetzt. Dort kannst du ganz genau angeben, welche Ordner zu sanitizen willst. Teste am besten erst mal mit kleineren Ordnern.

**Comment by Defcon0** [comment]
Ich habe gerade Version 2.2.0 veröffentlicht. Dort wurde das Error-Handling im neuen Command nochmal verbessert. Bitte nutze diese Version.
