### ISSUE TITLE
Missing Symfony 5 support

### ISSUE THREAD

**Issue by cgpro** [heimrichhannot/contao-filename-sanitizer-bundle#13]
`Attempted to load class "Event" from namespace "Symfony\Component\EventDispatcher".
Did you forget a "use" statement for e.g. "Symfony\Contracts\EventDispatcher\Event", "Spatie\SchemaOrg\Event", "Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Event" or "FOS\HttpCache\Event"?`

Passiert, wenn ich über die Dateiverwaltung einen Testordner anlege. Ich hab bei Packagist gesehen, dass Contao ^4.4 als Dependency eingetragen ist. Ist geplant das bis 4.12 zu "kompatibilisieren"? 😉

**Comment by koertho** [comment]
Das Bundle ist wohl noch nicht Symfony 5 kompatibel und wir haben nicht bei allen Bundles die Abhängigkeiten korrekt in der composer.json definiert. Wir selber arbeiten nur mit LTS-Versionen, daher ist das noch nicht aufgefallen. 
Irgendwann werden wir das schon ändern, aber das hat bis zur nächsten LTS keine Prio für uns.

**Comment by cgpro** [comment]
Alles gut, danke für die Info. Zum entwickeln komm ich erst mal ohne der Erweiterung klar, aber die ist super praktisch für Lazy-Customer-Filenames 😬.

**Comment by Defcon0** [comment]
OK, wir haben intern verabredet, dass wir punktuell die Module bei Bedarf für Symfony 5 freigeben. Die Abhängigkeiten machen wir in Zukunft auch konsequenter. Schau dir bitte mal v2.4.0 an, da müsste alles gehen :-)

**Comment by cgpro** [comment]
Funktioniert jetzt wunderprächtig! 🥳
