### ISSUE TITLE
Trennzeichen-Einstellungen

### ISSUE THREAD

**Issue by Xirdion** [heimrichhannot/contao-filename-sanitizer-bundle#2]
This is a very helpful extension and works great.
But i think there is a mistake in the translations for the settings.
![screenshot from 2019-01-18 11-15-21](https://user-images.githubusercontent.com/17783055/51380691-94200b00-1b12-11e9-980f-36d179f7241d.png)

The headline is telling you to not separate the signs, but the helper-text below tells the opposite.

**Comment by Defcon0** [comment]
You are absolutely right ;-) Fixed in 1.1.1.
