### ISSUE TITLE
German Umlaute

### ISSUE THREAD

**Issue by Acta2000** [heimrichhannot/contao-filename-sanitizer-bundle#4]
Hallo, 

gibt es eine Möglichkeit Umlaute nicht zu entfernen sondern aus ä ggf. ae bzw Ä ae zu machen?

**Comment by Defcon0** [comment]
Hi,

man könnte ein neues Feld vom Typ "multiColumnEditor" anlegen, in dem man Paare von "Zu ersetzendes Zeichen" und "Zielzeichen" hinzufügen kann. Diese würden dann nach der Sanitation angewendet werden.

Traust du dir einen Pull Request zu? Aktuell ist Zeit knapp und ein PR wäre willkommen.

**Comment by Acta2000** [comment]
Puh da muss ich leider zugeben dass, ich mit Github kaum Erfahrung habe. In deiner Contao 3 Version hattest du ja schon ein Eine Variante drin https://github.com/heimrichhannot/contao-upload_filename_sanitizer/blob/74379868ee2bd0229665cda7b83aed3bc6ad184f/classes/Hooks.php#L28

**Comment by Defcon0** [comment]
So, Version 1.2.0 ist fertig. Unter anderem gibt es dort auch die Möglichkeit, beliebige Zeichenersetzungen zu machen. @Acta2000 Kannst du bitte mal testen, ob es bei dir jetzt funktioniert?

**Comment by Acta2000** [comment]
Ich habe Version 1.2.0 installiert. Sehe aber leider die Tabelle zum Eintragen der Zeichen nicht in den Einstellungen. Var/Cache gelöscht. Composer Update gemacht... 

Die letzte Einstellmöglichkeit ist:

> Zu entfernende führende und schließende Zeichen (Leerzeichen werden immer entfernt; direkt hintereinander, nicht durch Kommata oder Leerzeichen trennen!)

**Comment by Acta2000** [comment]
>  - Updating twig/twig (v1.37.1 => v1.38.2): Downloading (100%)
>   - Updating tijsverkoyen/css-to-inline-styles (1.5.5 => 2.2.1): Downloading (100%)
>   - Updating heimrichhannot/contao-utils-bundle (2.81.0 => 2.83.1): Downloading (100%)
>   - Updating heimrichhannot/contao-filename-sanitizer-bundle (1.1.2 => 1.2.0): Downloading (100%)
>   - Updating contao/conflicts (dev-master 2b35d37 => dev-master 04c0e80)

In der Localconfig wird folgendes hinterlegt.

`
$GLOBALS['TL_CONFIG']['fs_charReplacements'] = 'a:4:{i:0;a:3:{s:6:"source";s:2:"ä";s:6:"target";s:2:"ae";s:10:"ignoreCase";b:1;}i:1;a:3:{s:6:"source";s:2:"ö";s:6:"target";s:2:"oe";s:10:"ignoreCase";b:1;}i:2;a:3:{s:6:"source";s:2:"ü";s:6:"target";s:2:"ue";s:10:"ignoreCase";b:1;}i:3;a:3:{s:6:"source";s:2:"ß";s:6:"target";s:2:"ss";s:10:"ignoreCase";b:1;}}';
`

**Comment by Acta2000** [comment]
Achso: Getestet mit Contao 4.4  ohne Contao Manager

**Comment by Defcon0** [comment]
Ich hatte die Abhängigkeit (multiColumnEditor) in der composer.json vergessen. Ist behoben in 1.2.1

**Comment by Acta2000** [comment]
Getestet und funktioniert. Umlaute werden auch geändert. 
Einzig die Icons für die Buttons delete und copy werden nicht angezeigt.

Laut IE Debugger ist  im Pfad der Datei ein "/" vor system zu viel
Pfad unter Settings:

> /system/themes/flexible/icons/copy.svg

Pfad unter Artikel:

> system/themes/flexible/icons/delete.svg

**Comment by Acta2000** [comment]
Im IE kann mann dadurch leider auch keine Neue Zeile hinzufügen! Im FF geht es. Auch neue Zeichen werden erkannt (getestet mit § zu pragraph)

**Comment by Defcon0** [comment]
Welche Version vom IE nutzt du? Das Icon-Problem kann ich in IE 11 und im Edge (beides Windows 10) nicht reproduzieren. Den anderen Bug schon.

**Comment by Acta2000** [comment]
Also ich nutze Windows Server 2016:

Die Standard Icons von Contao werden angezeigt. Die Icons in deiner Erweiterung nur dann, wenn ich das anführende "/" entferne.

Getestet mit IE 11, Firefox (aktuell)

```
<div class="actions">
                        <a href="/contaocomposer4/web/contao?do=settings&amp;ref=WOhspLvJ" class="add" title="">
                            <img src="system/themes/flexible/icons/copy.svg" width="16" height="16"> /icon wird angezeigt
                        </a>

                        <a href="/contaocomposer4/web/contao?do=settings&amp;ref=WOhspLvJ" class="delete" title="">
                            <img src="/system/themes/flexible/icons/delete.svg" width="16" height="16"> /icon wird nicht angezeigt 
                        </a>

                                            </div>
```

**Comment by Defcon0** [comment]
OK, das Hinzufügen-Problem im IE befand sich in https://github.com/heimrichhannot/contao-multi-column-editor-bundle . Nach umfangreichem Refactoring in diesem Modul kannst du contao-filename-sanitizer-bundle nun auf die letzte Version aktualisieren. Dort sollte alles nun auch im IE/Edge funktionieren.

Sag mir bitte Bescheid, ob nun alles klappt.

**Comment by Acta2000** [comment]
So update getan. Var/cache gelöscht -> Systemeinstellungen -> Alles bereinigt

Einstellungen -> ICONS sind nun im IE und FireFox da. 

Klick auf löschen führt zum Reload der Website, Klick auf "Plus" führt ebenfalls zum Reload der Seite. Zeilen werden jedoch weder gelöscht noch hinzugefügt (Firefox und Ie). 

Sortieren Button zeigt keine Wirklung. Gedrückthalten und ziehen -> macht er nix, bei Einzelklick wird Seite neu geladen.

**Comment by Defcon0** [comment]
Kannst du bitte den Cache deines Browsers leeren? Werden auf der Konsole Fehler geworfen?

**Comment by Acta2000** [comment]
Cache geleert -> keine Änderung in beiden Browsern.

Im Firefox sagt die Konsole:

```
ReferenceError: Sortable is not defined[Weitere Informationen] contao-multi-column-editor-bundle.js:1:13530
    o1Lx http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    n http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    3K4J http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    n http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    <anonym> http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    <anonym> http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
```

**Comment by Defcon0** [comment]
So, da waren doch noch ein paar Dinge noch nicht ganz ausgefeilt. Kannst du bitte auf 1.3.1 updaten? Bei mir funktioniert es jetzt in Firefox und IE11. Chrome ging ja schon immer.

**Comment by Acta2000** [comment]
```
- Updating heimrichhannot/contao-utils-bundle (2.83.1 => 2.84.0): Downloading (100%)
  - Updating heimrichhannot/contao-multi-column-editor-bundle (2.0.2 => 2.0.3): Downloading (100%)
  - Updating heimrichhannot/contao-filename-sanitizer-bundle (1.3.0 => 1.3.1): Downloading (100%)
```

Cache gelöscht - > Browser Cache gelöscht  -> Keine Änderung

```
ReferenceError: Sortable is not defined[Weitere Informationen] contao-multi-column-editor-bundle.js:1:13651
    o1Lx http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    n http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    3K4J http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    n http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    <anonym> http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
    <anonym> http://localhost/contaocomposer4/web/bundles/heimrichhannotcontaomulticolumneditor/js/contao-multi-column-editor-bundle.js:1
```

**Comment by Defcon0** [comment]
OK, ich glaube, jetzt haben wir den Fehler gefunden. Die Stelle, die bei dir einen Fehler wirft, wirft bei uns keinen, weil wir noch eine andere Bibliothek installiert hatten, wo sortablejs mitgeliefert wurde. Ich habe jetzt den Import dynamisiert, wodurch es bei dir zu keinen Problemen mehr kommen sollte.

Du müsstest multi-column-editor auf 2.0.4 updaten. Danke fürs Testen!

**Comment by Acta2000** [comment]
Jetzt funktioniert es. Sehr sehr schöne Ergänzung zum Contao-Standart.

**Comment by Defcon0** [comment]
Wunderbar. Finally ;-) Danke für die Info!
