### ISSUE TITLE
Frontend Uploads

### ISSUE THREAD

**Issue by 9teufel** [heimrichhannot/contao-filename-sanitizer-bundle#5]
Greift die Erweiterung auch für Frontend Uploads (Mitglieder Uploads ins Benutzerverzeichnis)?

**Comment by Defcon0** [comment]
Die Anwendung nutzt bei Uploads den Hook `postUpload`. Dieser wird meines Wissens im Frontend nicht ausgeführt. Da wir im Team nicht auf den Formular-Generator für Frontend-Formulare setzen (wegen des fehlenden DCA-Supports), haben wir das auch nicht umgesetzt. Wenn du einen Pull-Request bereitstellst, schauen wir uns diesen aber natürlich gern an und mergen ihn gegebenenfalls. Würdest du dir das zutrauen?

**Comment by 9teufel** [comment]
Leider kann ich keinen Pull-Request bereitstellen.

OT: Wenn ihr den Formular-Generator nicht nutzt, was dann?

**Comment by Defcon0** [comment]
Wir nutzen das hier (eine Eigenentwicklung): https://github.com/heimrichhannot/contao-frontendedit

Mit diesem Modul kannst du beliebige Entitäten im Frontend bearbeiten. Du musst einfach ein "Frontendedit-Leser"-Modul anlegen, die Tabelle auswählen und die Felder, die ausgegeben werden sollen, auswählen.
