### ISSUE TITLE
JS-Skripte im Frontend durch Bundle?

### ISSUE THREAD

**Issue by ngdot** [heimrichhannot/contao-filename-sanitizer-bundle#6]
Hi, ich würde wirklich gerne die Funktionalität dieser Erweiterung für den Datei-Upload verwenden. Leider werden durch dieses Bundle weitere Erweiterungen mitinstalliert, die drei JS-Skripte in den Head-Teil der Website einbauen. 

Gibt es eine Möglichkeit NUR den filename-sanitizer zu verwenden? 
Ich möchte meine Seite nicht unnötig aufblasen mit JS-Skripten die nicht verwendet werden.

Das Package "contao-upload_filename_sanitizer" enthält leider keine Einstellungsmöglichkeiten und soll ja sowieso nicht mehr verwendet werden.

Freue mich auf deine Antwort!

**Comment by koertho** [comment]
@NicolasGoerlach Die Abhängigkeiten werden für die Funktionalität des Bundles benötigt. Das Bundle kann prinzipiell auch im Frontend verwendet werden, daher werden die JS-Dateien auch im Frontend eingebunden. Der Contao Core bietet da leider wenig Möglichkeiten, hier zu Filtern. Aus diesem Grund nutzen wir das [Encore Bundle](https://github.com/heimrichhannot/contao-encore-bundle), damit kann Seiten-genau eingestellt werden, was (nicht) eingebunden werden soll. 
Alternativ könntest du dir unser altes, aber nicht mehr weiterentwickeltes, [Contao Components](https://github.com/heimrichhannot/contao-components) anschauen und die Assets damit deaktivierbar machen. 
Last but not least gibt es immer noch die Möglichkeit, die Assets über einen Hook wieder rauszuschmeißen (machen die beiden vorigen Bundles nicht anders). 
Grundsätzlich empfehlen wir den Encore-Weg, da man hier einen modernen und Symfony-präferierten Weg nutzt. Braucht Anfangs ein wenig Einarbeitung und Umstellung, aber lohnt sich.

**Comment by 9teufel** [comment]
Auf die selbe Problematik bin ich auch gestoßen (JS im Frontend).
Schade dass sich das nicht konfigurieren lässt.
