### ISSUE TITLE
Sanitizer als CMD-Scipt

### ISSUE THREAD

**Issue by Acta2000** [heimrichhannot/contao-filename-sanitizer-bundle#8]
Um auf einer größeren Installation den Sanitizer vorab einmal durchlaufen zu lassen, wäre es schön, wenn es ein Sript für die CMD gibt.

**Comment by Defcon0** [comment]
Erledigt mit 2.1.0 . (Alle Infos siehe https://github.com/heimrichhannot/contao-filename-sanitizer-bundle/blob/master/README.md)

**Wichtig**: Da das Feature ganz neu ist, bitte lege UNBEDINGT ein Backup von `tl_files` und dem `files`-Ordner an!

**Comment by Defcon0** [comment]
Ich habe gerade Version 2.2.0 veröffentlicht. Dort wurde das Error-Handling im neuen Command nochmal verbessert. Bitte nutze diese Version.
