### ISSUE TITLE
Umlaut-Konvertierung funktioniert nicht richtig (Dateiupload)

### ISSUE THREAD

**Issue by ngdot** [heimrichhannot/contao-filename-sanitizer-bundle#9]
Möchte ich die Datei "DÖNER.jpg" hochladen, wird daraus "do-ner.jpg" obwohl in den Einstellungen hinterlegt ist, dass aus "ö" => "oe" werden soll.
Komisch ist, dass es bei der Erstellung eines Ordners funktioniert. Hier wird aus "DÖNER" => "doener". Jemand eine Idee was hier falsch läuft?

![Bildschirmfoto 2019-07-25 um 12 05 12](https://user-images.githubusercontent.com/8327905/61865924-7920c000-aed4-11e9-83c2-297907bd234b.jpg)

![Bildschirmfoto 2019-07-25 um 12 04 41](https://user-images.githubusercontent.com/8327905/61865904-6ad2a400-aed4-11e9-8bd7-c64231814ca3.jpg)

**Comment by Defcon0** [comment]
Bekomme ich nicht reproduziert. Habe genau das gemacht, was du schreibst. Kannst du es bitte mit der letzten Version versuchen?

Kann es daran liegen, dass du einen Mac nutzt (sieht zumindest so aus)? Da gibt es öfter Umlautprobleme.

**Comment by Defcon0** [comment]
OK, es lag scheinbar am Mac. Sollte mit v2.2.1 behoben sein.
